name: cdn-builds

on:
    push:
        branches: [main]
    pull_request: # used for testing, will be removed before merging
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v2

            - uses: denoland/setup-deno@main
              with:
                  deno-version: v1.x

            - name: Bundle
              run: deno run --unstable --allow-net --allow-run --allow-read=.. --allow-write=bundles/ bundle-es6.ts
              working-directory: bundling

            - name: Install headers
              run: cp -v netlify.toml bundles/
              working-directory: bundling

            - name: Show output
              run: find bundling

            - name: Netlify deployment
              uses: nwtgck/actions-netlify@v1.1.11
              with:
                  publish-dir: bundling/bundles
                  production-branch: main
              env:
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
